name: polymer_elements
author: Vittorio Ballestra <vittorio.ballestra@gmail.com>
homepage: https://github.com/dam0vm3nt
description: Polymer-2 support for Dart

version: 2.0.0-preview.1+1
dependencies:
  js: any
  polymer_element: ^2.0.0
  polymerize:  ^0.9.0
transformers:
 - polymerize
